version: '3.8'

services:
  #lets try to spin up the build image for production here specified using dockerfile.prod
  postgres:
    image: postgres:15-alpine # use pre-built PostgreSQL image
    restart: always
    container_name: testimony-cont-db
    ports:
      - '5433:5432' # expose ports from computer
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data #persist data

volumes:
  postgres_data: #named volume for database storage

